<?php
/**
 * Copyright © Thana', Inc. All rights reserved. 
 */
 
/** @var CustomerLogin\Tracking\Block\Account\PreviousLogin $block */
?>
<?php if (!$block->getLastLoginTransactionInformationBeforeCurrentLogin()) : ?>
    <div class="container">
    <div class="row">
        <h3>Previous login data of current login</h3>
        <div class="col-xs-12 col-xs-6">
            <h5>Customer ID: <?php echo $block->getPreviouslyOfCurrentLoginId(); ?></h5> 
        </div>
        <div class="col-xs-12 col-xs-6">
            <h5>Customer Address: <?php echo $block->getPreviouslyOfCurrentLoginIpAddress(); ?></h5> 
        </div>
    </div>
    <div class="row"> 
        <div class="col-xs-12 col-xs-6">
            <h5>Device Type <?php echo $block->getPreviouslyOfCurrentLoginUserAgent(); ?></h5> 
        </div>
        <div class="col-xs-12 col-xs-6">
            <h5>Date/Time Login: <?php echo $block->getPreviouslyOfCurrentLoginTime(); ?></h5> 
        </div>
    </div>
    </div>
<?php else : ?>
	<div class="message info empty">
		<span><?php echo $block->getMessageForFirstLogin(); ?></span>
	</div>
	 
<?php endif; ?>